[requirement.bootloaders]
description = "These requirements targets the functionality of the Crazyflie bootloaders."

[requirement.bootloaders.reset_to_bootloader]
description = """
It must be possible, by way of radio, to reset to bootloader from main firmware.
"""
rational = "Design"

[requirement.bootloaders.reset_to_firmware]
description = """
It must be possible, by way of radio, to reset to main firmware from bootloader.
"""
rational = "Design"

[requirement.bootloaders.reliability]
description = "Switching between bootloader and main firmware"
rational = "Design"
background = """
The design is that there should never be any timing dependencies in the python API
So we should be able to go back and forth between bootloader and main firmware for ever.
However, testing infinity is hard so, as a compromise, we are testing with
20 iterations per device.
"""
iterations = 20
