[requirement.decks]
description = "These requirements target the Crazyflie expansion decks."

[requirement.decks.basic]
description = """
It must be possible to detect, by way of the parameter interface, which decks
that are currently detected and initilized correctly on the Crazyflie.
"""
rational = "Design"
