name: Crazy Stab Lab 🗡️

# Controls when the action will run.
on:
  workflow_dispatch
jobs:
  testsuite_at_crazylab:
    runs-on: self-hosted
    container:
      image: python
      options: --privileged
    env:
      CRAZY_SITE: crazylab-malmö
    steps:
      - name: Install libusb
        run: |
          apt update
          apt install libusb-1.0-0
      - name: Install pytest
        run: pip3 install pytest
      - name: Install Crazyflie python library
        run: pip3 install git+https://github.com/bitcraze/crazyflie-lib-python.git@master
      - name: Check out sources
        uses: actions/checkout@v2
      - name: Download latest firmware files
        with:
          repo: bitcraze/crazyflie-release
          workflow: nightly.yml
        uses: dawidd6/action-download-artifact@v2.14.0
      - name: Run test suite
        run: pytest --verbose --junit-xml $CRAZY_SITE-$(date +%s).xml
