name: Crazy Stab Lab 🗡️

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
  - cron:  '0 2 * * *'

jobs:
  testsuite_at_crazylab:
    runs-on: self-hosted
    container:
      image: python
      options: --privileged
    env:
      CRAZY_SITE: crazylab-malmö
    steps:
      - name: Install libusb
        run: |
          apt update
          apt install libusb-1.0-0
      
      - name: Install pytest
        run: pip3 install pytest
      
      - name: Install Crazyflie python library
        run: pip3 install git+https://github.com/bitcraze/crazyflie-lib-python.git@master
      
      - name: Check out sources
        uses: actions/checkout@v2
      
      - name: Download latest firmware files
        with:
          repo: bitcraze/crazyflie-release
          workflow: nightly.yml
        uses: dawidd6/action-download-artifact@v2.14.0

      - name: Upgrde devices to latest firmware
        run: python3 management/program.py --file nightly/firmware-cf2-nightly.zip
      
      - name: Run test suite
        run: pytest --verbose --junit-xml $CRAZY_SITE-$(date +%s).xml tests/QA

      - name: Checkout Crazyflie python library
        uses: actions/checkout@v2
        with:
          repository: bitcraze/crazyflie-lib-python
          path: crazyflie-lib-python

      - name: Run Crazyflie python library examples
        run: |
          python3 -u utils/run_examples.py --path crazyflie-lib-python
